### ISSUE TITLE
Xperia 10IV (pdx225) missing from hardware repository

### ISSUE THREAD

**Issue by ekaats** [XperiaLabs/hardware_sony#1]
There is no branch for the Xperia 10 IV (pdx225/Murray) device. I've been using the one from XperiaBrickers (https://github.com/XperiaBrickers-10IV/hardware_sony) but suspect that it is not updated to reflect changes in the device repositories. For example "health/aidl" found in that repo is now flagged as a duplicate module.

**Comment by ghost** [comment]
yeah working on it

**Comment by ghost** [comment]
Done
